### ISSUE TITLE
Failed Test on matching of property in Text/PrintSpec

### ISSUE THREAD

**Issue by m15k** [ZHaskell/z-data#29]
Appear to have a failure when comparing a negative number in test[..] Text/Print toString v /= show v

Error:
`  test/Z/Data/Text/PrintSpec.hs:67:5: 
  1) Z.Data.Text.Print, Print Base instances, Value Show instance === ToText instances
       Falsified (after 5 tests):
         Number -2.0
         "Number (-2.0)" /= "Number -2.0"
`
Tested against: GHC 8.8.3 on Linux

**Comment by winterland1989** [comment]
Which version do you use? It should have been fixed in https://github.com/ZHaskell/z-data/commit/232df5544593ef2f31abc9fadb56c9cfbf667c1f (which is released in v0.8.3.0)

**Comment by m15k** [comment]
The version I'm using is [0c1763e](https://github.com/ZHaskell/z-data/commit/4385ae19b2683b0446a95f19e0caf75400c1763e)

**Comment by winterland1989** [comment]
I should bump the `scientific` version bound to `0.3.7` because they change the `Show` instance: https://hackage.haskell.org/package/scientific-0.3.7.0/changelog. You can manually limit `scientific` 's version to get the new parentheses change.

**Comment by winterland1989** [comment]
Done in #498557f
