### ISSUE TITLE
Lack of some* and many* combinators in Z.Data.Parser

### ISSUE THREAD

**Issue by zypeh** [ZHaskell/z-data#33]
I am actually writing some parser benchmark compared with [Flatparse](https://github.com/zypeh/flatparse/commit/180229f62bb3c9984cdbb8ede70806a689b0fa97).

And I found that `Z.Data.Parser` is lacking something like
1. `many_` or `some_` that skips the returned value. The functions I can use are `skipWhile` or `skipWord8` and that is limiting.
2. `many` or `some` combinators to compose our parser so we no need to create a custom loop.
3. `<|>` backtrack.

I just want to know that for (1) and (2) are they design on purpose? Can we add them in Z-Data?

For (3) - I know this is something that likely to cause performance issue but I saw flatparse has so-called `branch` that fused multiple branches into one CPS that we can try.

**Comment by winterland1989** [comment]
Like the document put:

> Use [parser-combinators](https://hackage.haskell.org/package/parser-combinators) to get combinators based on Applicative or Monad instance, such as manyTill, sepBy, etc.

So if you want to add `many_` and `some_`, I think the best place to add them is [parser-combinators](https://hackage.haskell.org/package/parser-combinators). And of course, I'm OK with a patch re-export some modules from `Z.Data.Parser`.
